#!/usr/bin/env python3
"""Deterministic journal compiler (crux convention).

Usage: compile-journal.py [repo-root]

Renders the compiled journal view from the write-once fragments directory in
ascending id order, prepending the base journal file verbatim when the
repository has one (adopted history is preserved untouched; fresh repositories
simply have no base file). Paths come from `.claude/crux.json` when
present, else the defaults below.

Fragment format: YAML frontmatter with `id: <int>` (monotonic at land time)
and `date: YYYY-MM-DD`; body = the entry. No author names in fragment text —
attribution resolves via git blame on the fragment file.

Exit 2 on duplicate or missing ids; byte-deterministic otherwise (the output
depends only on the sources, never on run time).
"""
import json
import os
import re
import sys

DEFAULTS = {
    "journal_dir": "experiments/journal-fragments",
    "journal_file": "experiments/journal.md",
    "compiled_file": "experiments/journal-compiled.md",
}


def load_paths(root):
    cfg = dict(DEFAULTS)
    try:
        with open(os.path.join(root, ".claude", "crux.json"),
                  encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict):
            for key in DEFAULTS:
                value = data.get(key)
                if isinstance(value, str) and value.strip():
                    cfg[key] = value.strip().strip("/")
    except Exception:
        pass
    return cfg


def main(root="."):
    cfg = load_paths(root)
    fdir = os.path.join(root, cfg["journal_dir"])
    base = os.path.join(root, cfg["journal_file"])
    out = os.path.join(root, cfg["compiled_file"])

    frags = []
    for name in sorted(os.listdir(fdir)) if os.path.isdir(fdir) else []:
        if not name.endswith(".md"):
            continue
        text = open(os.path.join(fdir, name), encoding="utf-8").read()
        m = re.match(r"---\n(.*?)\n---\n?(.*)", text, re.S)
        if not m:
            print("compile-journal: fragment without frontmatter: %s" % name)
            return 2
        fm, body = m.group(1), m.group(2)
        idm = re.search(r"^id:\s*(\d+)\s*$", fm, re.M)
        if not idm:
            print("compile-journal: fragment without id: %s" % name)
            return 2
        frags.append((int(idm.group(1)), name, body.strip()))

    ids = [i for i, _, _ in frags]
    if len(ids) != len(set(ids)):
        print("compile-journal: duplicate ids")
        return 2
    frags.sort()

    header = ("# Journal — compiled view (build artifact)\n"
              "<!-- generated by scripts/compile-journal.py — do not edit; the "
              "sources are\nthe base journal file (if any) and the write-once "
              "fragments directory -->")
    parts = []
    if os.path.isfile(base):
        parts.append(open(base, encoding="utf-8").read().rstrip("\n"))
        parts.append("\n---\n\n" + header)
    else:
        parts.append(header)
    for i, name, body in frags:
        parts.append("\n<!-- entry %d: %s -->\n%s" % (i, name, body))

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    open(out, "w", encoding="utf-8").write("\n".join(parts) + "\n")
    print("compiled %d fragment(s) -> %s" % (len(frags), out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "."))
